### ISSUE TITLE
Only works with catkin_make and not catkin build

### ISSUE THREAD

**Issue by rickstaa** [rickstaa/.ros_conda_wrapper#4]
**Describe the bug**
The conda wrapper appears only to work with the `catkin_make` package nad not the`catkin build` tool.

**To Reproduce**
1. Source the `.conda_wrapper`
2. Try to build a ROS package using `catkin build`
3. See error:

```
catkin build -DPYTHON_EXECUTABLE="$(which python)" -DPYTHON_LIBRARY="$(find $(which python | sed -e 's/\/bin\/python//') -iname libpython*m.s
o)" -DPYTHON_INCLUDE_DIR="$(find $(which python | sed -e 's/\/bin\/python//')/include -iname python*m)"
Traceback (most recent call last):
  File "/usr/bin/catkin", line 11, in <module>
    load_entry_point('catkin-tools==0.4.5', 'console_scripts', 'catkin')()
  File "/opt/conda/envs/autograsp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 489, in load_entry_point
    return get_distribution(dist).load_entry_point(group, name)
  File "/opt/conda/envs/autograsp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2843, in load_entry_point
    return ep.load()
  File "/opt/conda/envs/autograsp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2434, in load
    return self.resolve()
  File "/opt/conda/envs/autograsp/lib/python3.7/site-packages/pkg_resources/__init__.py", line 2440, in resolve
    module = __import__(self.module_name, fromlist=['__name__'], level=0)
  File "/usr/lib/python2.7/dist-packages/catkin_tools/commands/catkin.py", line 30, in <module>
    from catkin_tools.config import get_verb_aliases
  File "/usr/lib/python2.7/dist-packages/catkin_tools/config.py", line 18, in <module>
    import yaml
  File "/opt/conda/envs/autograsp/lib/python3.7/site-packages/yaml/__init__.py", line 374
    class YAMLObject(metaclass=YAMLObjectMetaclass):
                              ^
SyntaxError: invalid syntax
```

**Expected behavior**
The package should build succesfully like this is the case while using `catkin_make`.

**Desktop (please complete the following information):**
 - OS: Linux ubuntu 16.04

**Possible solution**
Implement additional wrapping around the catkin build command [see this command](https://medium.com/@beta_b0t/how-to-setup-ros-with-python-3-44a69ca36674). Making sure it points to a python2 environment. Or the solution given by [gvdhoorn](https://answers.ros.org/question/237613/how-to-define-ros-kinetic-to-use-python3-instead-of-python27/)

**Comment by rickstaa** [comment]
Fixed in [v0.0.4](https://github.com/rickstaa/.ros_conda_wrapper/releases/tag/v0.0.4) (Released).
